# Generated by Django 3.2.12 on 2022-06-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room_class',
            field=models.CharField(max_length=100),
        ),
    ]
